clc;
close all;
clear all;
RGB = imread('saturn.png');
I = rgb2gray(RGB);
G = imnoise(I,'Gaussian',0,0.02);
H = wiener2(G,[10 10]);
K = fspecial('disk',10);
blurred = imfilter(H,K,'replicate');
subplot(2,3,1);
imshow(RGB);
subplot(2,3,2);
imshow(I);
subplot(2,3,3);
imshow(G);
subplot(2,3,4);
imshow(H);
subplot(2,3,5);
imshow(blurred);